name: auto_injector
description: Automatic Dependency Injection System, but without build_runner :)
version: 1.2.0
repository: https://github.com/Flutterando/auto_injector

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  meta: '>=1.5.0 <2.0.0'
  uuid: ^3.0.7

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ^1.16.0
